version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  # to start a container with test script from docker compose
  # test:
  #   container_name: test
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - '.:/app'
  #     - '/app/node_modules'
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   command: ["npm","run","test"]